#!/bin/bash
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageName=${packageHome##*/}
profilePath=${profileDirPath}/${packageName}.sh
mkdir -p ${profileDirPath}
#echo "#${packageName%%_*}_HOME=${packageHome}" >> ${profilePath}
echo "[[ -n \${PERL5LIB} ]] && export PERL5LIB=\${PERL5LIB}:${packageHome}/PERL5LIB/lib/perl5" > ${profilePath}
echo "[[ -z \${PERL5LIB} ]] && export PERL5LIB=${packageHome}/PERL5LIB/lib/perl5" >> ${profilePath}
